### ISSUE TITLE
Class operators related issues 

### ISSUE THREAD

**Issue by diffore** [Andr3as/Codiad-Beautify#5]
Hi, 

Not sure if you are still supporting this, but it would be really cool if you add support for class related operators. You can check these snapshots to see what I mean: 

This: 
![1](https://cloud.githubusercontent.com/assets/9458937/8441219/9ad46bc2-1f7f-11e5-9b64-50c7839ce837.jpg)

Became this  :(   
![2](https://cloud.githubusercontent.com/assets/9458937/8441220/9ad49e94-1f7f-11e5-9102-7b50e4b75ea4.jpg)

So, as you may guess, beautify breaks everything :(   I guess it's a third party library issue but maybe you can fix it. 

In any case big thanks  for this plugin. 

Regards, 
Mikhail

**Comment by Andr3as** [comment]
I created a dirty fix (7d29473) for your problem, but I'm not happy with it.

**Comment by Andr3as** [comment]
See #10 for further developments.
