### ISSUE TITLE
Use Beautify lost the cursor position

### ISSUE THREAD

**Issue by loclamor** [Andr3as/Codiad-Beautify#6]
It would be great if when using beautify cursor position could be kept.
Indeed, using Ctrl-Alt-b make cursor position at end of file and save, with Beautify enable, make cursor position at file start.

I understand that keep original cursor position is sometimes not possible when reformating file, but it would be great if the cursor position could stay at the nearest position as possible as the original position, especially on large files !

**Comment by Andr3as** [comment]
Current solution is opt-in: you have to activate it in the settings.

**Comment by loclamor** [comment]
Hi,

Thanks you for fixing this, it works fine with Ctrl-Alt-b.

But it don't work on beautify-ing on save.
I think the guess-position stufs should be at the end of init's beautifyContent function.

However, thanks for your work, I use some of your plugins in Codiad, and it's usefull. Thanks a lot ;)
